log:
  level: DEBUG

authentication:
  required: true
  methods:
    token:
      enabled: true
      bootstrap:
        token: test-token-123

storage:
  type: object
  object:
    type: s3
    s3:
      region: us-east-1
      bucket: flipt
      endpoint: http://minio:9000
      poll_interval: "5s"
